### ISSUE TITLE
Inconsistent icons

### ISSUE THREAD

**Issue by lee-kagiso** [benekastah/neomake#124] opened 2015-05-06 10:00 UTC
Neomake:

![neomake](https://cloud.githubusercontent.com/assets/11830393/7490870/63a88820-f3e4-11e4-9b97-f1784f62b69c.png)

Neomake!:
![neomake](https://cloud.githubusercontent.com/assets/11830393/7490872/6a39082c-f3e4-11e4-8c1d-8efaa5dd009a.png)

**Comment by benekastah** [comment] 2015-05-07 06:46
`:Neomake` and `:Neomake!` don't necessarily do the same things. Each could run different programs with different errorformats. What you are seeing is one configuration reporting your error as an error and the other is reporting it as a warning. I don't know what your configuration is like, but I'm guessing this is probably not a bug. If you're running the same programs with the same errorformat, it could be a bug.

**Comment by benekastah** [comment] 2015-05-07 06:52
Closing for now. Let me know if you still have reason to believe it's a bug :)

**Comment by lee-kagiso** [comment] 2015-05-07 07:12
I am using flake8, and everything gets reported as an error with Flake8.

I haven't configured anything re. your plugin.

To be honest I don't intend using Neomake!, but I do believe that there is
some bug here.

**Comment by benekastah** [comment] 2015-05-07 15:24
Thanks for reporting. It sounds like there is a bug after all.

**Comment by Neki** [comment] 2015-05-07 16:43
flake8 is currently defined as a file maker (not a project maker), if you have not done any additional configuration it should not be used as a project maker. I can't reproduce this ; calling `:Neomake!`result in makeprg being used, not flake8 (without any specific configuration).
Could you execute `:let g:neomake_logfile="neomake.log"`, then run `:Neomake!` and paste the content of `neomake.log`?

**Comment by lee-kagiso** [comment] 2015-05-18 08:49
Sorry for taking forever to do this, so now things are different, Neomake shows the exclamation mark and Neomake shows nothing.

Here are the logs:

*Neomake*:
```
  1 2015-05-18T10:44:42+0200 Log level 2: Neomake: Starting: python -c from __future__ import print_function^@from sys import argv, exit^@if len(argv) != 2:^@    exit(1)^@try:^@ 
  2 2015-05-18T10:44:43+0200 Log level 2: Neomake: Starting: flake8 /home/lee/Code/django_auth/auth_backend/models.py
  3 2015-05-18T10:44:43+0200 Log level 1: Neomake: python complete with exit code 0 
  4 2015-05-18T10:44:43+0200 Log level 3: Neomake: Cleaning old signs: {1: {2: 5000}}
  5 2015-05-18T10:44:43+0200 Log level 3: Neomake: Unplacing sign: sign unplace 5000
  6 2015-05-18T10:44:43+0200 Log level 3: Neomake: flake8 stdout: /home/lee/Code/django_auth/auth_backend/models.py:2:1: I100 Imports statements are in the wrong order. from date
  7 2015-05-18T10:44:44+0200 Log level 3: Neomake: flake8 stdout:                   
  8 2015-05-18T10:44:44+0200 Log level 3: Neomake: flake8 stdout done.              
  9 2015-05-18T10:44:44+0200 Log level 3: Neomake: flake8 processing 2 lines of output
 10 2015-05-18T10:44:44+0200 Log level 3: Neomake: Placing sign: sign place 5000 line=2 name=neomake_warn buffer=1
 11 2015-05-18T10:44:44+0200 Log level 1: Neomake: flake8 complete with exit code 1 
~           
```        

*Neomake!* 
```
2015-05-18T10:44:58+0200 Log level 2: Neomake: Starting: /bin/bash -c make
2015-05-18T10:44:58+0200 Log level 3: Neomake: makeprg stderr: make: *** No targets specified and no makefile found.  Stop.
2015-05-18T10:44:58+0200 Log level 3: Neomake: makeprg stderr: 
2015-05-18T10:44:58+0200 Log level 3: Neomake: makeprg stderr done.
2015-05-18T10:44:58+0200 Log level 3: Neomake: makeprg processing 2 lines of output
2015-05-18T10:44:58+0200 Log level 1: Neomake: makeprg complete with exit code 2
2015-05-18T10:44:58+0200 Log level 3: Neomake: Cleaning old signs: {1: {2: 5000}}
2015-05-18T10:44:58+0200 Log level 3: Neomake: Unplacing sign: sign unplace 5000
```

**Comment by Neki** [comment] 2015-05-18 11:12
This is the expected behaviour. `:Neomake` correctly calls `flake8` (in the default configuration) and displays the sign.

`:Neomake!` without arguments calls your `makeprg`, which by default is `make` (and thus does nothing in your Python project since you do not have a Makefile).

If you want to call `flake8` on your project, you can define a project maker (see `:h neomake`) or set your `makeprg` and `errorformat`: 
```
:set makeprg=flake8
:set errorformat=' copy the error format from the flake8 maker in autoload/neomake/makers/ft/python.vim here '
```
and then call `:Neomake!`.

**Closed** 2015-05-18 11:12 UTC

**Comment by lee-kagiso** [comment] 2015-05-18 11:21
why do i get the exclamation mark (which is very whispy looking/not overly
visible) over the prominent x?

**Comment by Neki** [comment] 2015-05-18 11:33
flake8 is not reporting an error, but a mere warning, so you get the warning sign (the exclamation mark) instead of the error sign (the x). If you don't like this symbol, you can easily change it (`:h neomake_warning_sign`)
