### ISSUE TITLE
Error detected while processing function neomake#MakeHandler

### ISSUE THREAD

**Issue by sittim** [benekastah/neomake#311] opened 2016-02-17 14:50 UTC
Issue:

![selection_088](https://cloud.githubusercontent.com/assets/8825037/13110625/29d7ab88-d54f-11e5-89b1-2dea686b537b.png)

## init.vim contents

```viml
let g:neomake_cpp_cpplint_maker = {
            \ 'exe': 'cpplint'
            \ }
let g:neomake_cpp_enabled_makers = ['cpplint']

:autocmd! BufWritePost,VimEnter *.java Neomake 
:autocmd! BufWritePost,VimEnter,InsertLeave *.cpp Neomake

```
The error is random, it happens every so often.  Why would I get this error?

**Comment by benbarbour** [comment] 2016-02-17 19:31
I think this is a duplicate of #291

**Comment by sittim** [comment] 2016-02-17 19:41
OK, how do I apply the fix?  I have updated the plug-ins....

**Comment by sittim** [comment] 2016-02-17 22:29
OK, thanks, I also use neovim and vim-plugged, but, I tend to update plug-ins often, so I think I will just leave my hand editing and watch for a merge.

**Closed** 2016-02-19 18:29 UTC
